name: Merge-upstream-immortalwrt

env:
  REPO: moruiris/openwrt-packages

on:
  push:
    branches:
      - main
    paths:
      - './diy/immortalwrt.sh'
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [immortalwrt]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./diy/${{matrix.target}}.sh
        chmod +x ./diy/convert_translation.sh
        git clone -b ${{matrix.target}} https://github.com/${REPO}.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf * >/dev/null 2>&1
        $GITHUB_WORKSPACE/diy/${{matrix.target}}.sh
        $GITHUB_WORKSPACE/diy/convert_translation.sh
    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push --quiet "https://${GITHUB_TOKEN}}@github.com/moruiris/openwrt-packages.git" HEAD:${{matrix.target}}
    - name: delete-older-workflow
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 0
